//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eReview01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eReview01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1403880919_stop {
            get {
                object obj = ResourceManager.GetObject("1403880919_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADD1 {
            get {
                object obj = ResourceManager.GetObject("ADD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo nhập dữ liệu .
        /// </summary>
        internal static string AlertEnter {
            get {
                return ResourceManager.GetString("AlertEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner1 {
            get {
                object obj = ResourceManager.GetObject("banner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2 {
            get {
                object obj = ResourceManager.GetObject("banner2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tùy chọn &gt;&gt;.
        /// </summary>
        internal static string btnOptionColapseText {
            get {
                return ResourceManager.GetString("btnOptionColapseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tùy chọn &lt;&lt;.
        /// </summary>
        internal static string btnOptionExpanseText {
            get {
                return ResourceManager.GetString("btnOptionExpanseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cal {
            get {
                object obj = ResourceManager.GetObject("cal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cam {
            get {
                object obj = ResourceManager.GetObject("Cam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cam1 {
            get {
                object obj = ResourceManager.GetObject("Cam1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera_quan_sat_4 {
            get {
                object obj = ResourceManager.GetObject("camera-quan-sat-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel16 {
            get {
                object obj = ResourceManager.GetObject("Cancel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bạn chưa chọn.
        /// </summary>
        internal static string cboChose {
            get {
                return ResourceManager.GetString("cboChose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp..
        /// </summary>
        internal static string ChangePassword_ConfirmPasswordInvalid {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được trùng mật khẩu cũ..
        /// </summary>
        internal static string ChangePassword_NewPasswordSameOldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPasswordSameOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu mới..
        /// </summary>
        internal static string ChangePassword_NotFillNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NotFillNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu cũ..
        /// </summary>
        internal static string ChangePassword_NotFillOldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NotFillOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng..
        /// </summary>
        internal static string ChangePassword_OldPasswordInvalid {
            get {
                return ResourceManager.GetString("ChangePassword_OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra kết nối!.
        /// </summary>
        internal static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thoát khỏi chương trình không?.
        /// </summary>
        internal static string ClosingFormConfirm {
            get {
                return ResourceManager.GetString("ClosingFormConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Config_Address {
            get {
                return ResourceManager.GetString("Config_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerName.
        /// </summary>
        internal static string Config_CompanyName {
            get {
                return ResourceManager.GetString("Config_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa (các) bản ghi này không?.
        /// </summary>
        internal static string Confirm_WannaDeleteRecord {
            get {
                return ResourceManager.GetString("Confirm_WannaDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu bản ghi này không?.
        /// </summary>
        internal static string Confirm_WannaSaveRecord {
            get {
                return ResourceManager.GetString("Confirm_WannaSaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không kết nối được với máy chủ..
        /// </summary>
        internal static string ConnectionFail {
            get {
                return ResourceManager.GetString("ConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối thành công..
        /// </summary>
        internal static string ConnectSuccess {
            get {
                return ResourceManager.GetString("ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customers {
            get {
                object obj = ResourceManager.GetObject("customers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế toán trưởng.
        /// </summary>
        internal static string DBOptionKey_AccountingChief {
            get {
                return ResourceManager.GetString("DBOptionKey_AccountingChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế toán viên.
        /// </summary>
        internal static string DBOptionKey_AccountingStaff {
            get {
                return ResourceManager.GetString("DBOptionKey_AccountingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám sát trưởng.
        /// </summary>
        internal static string DBOptionKey_MonitorChief {
            get {
                return ResourceManager.GetString("DBOptionKey_MonitorChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trạm.
        /// </summary>
        internal static string DBOptionKey_StationName {
            get {
                return ResourceManager.GetString("DBOptionKey_StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãnh đạo trạm.
        /// </summary>
        internal static string DBOptionKey_TollCollectionChief {
            get {
                return ResourceManager.GetString("DBOptionKey_TollCollectionChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        internal static string DBOptionKey_UnitName {
            get {
                return ResourceManager.GetString("DBOptionKey_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Tất cả&gt;&gt;.
        /// </summary>
        internal static string Default_AllString {
            get {
                return ResourceManager.GetString("Default_AllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete16 {
            get {
                object obj = ResourceManager.GetObject("Delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap demo {
            get {
                object obj = ResourceManager.GetObject("demo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Do {
            get {
                object obj = ResourceManager.GetObject("Do", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Do1 {
            get {
                object obj = ResourceManager.GetObject("Do1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down4 {
            get {
                object obj = ResourceManager.GetObject("down4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_icon {
            get {
                object obj = ResourceManager.GetObject("edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editmode {
            get {
                object obj = ResourceManager.GetObject("editmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emblem_camera {
            get {
                object obj = ResourceManager.GetObject("emblem_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emblem_money {
            get {
                object obj = ResourceManager.GetObject("emblem_money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin mời nhập đầy đủ thông tin!.
        /// </summary>
        internal static string EnterFullInfo {
            get {
                return ResourceManager.GetString("EnterFullInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Cả hai&gt;&gt;.
        /// </summary>
        internal static string EnumCustomerType_All {
            get {
                return ResourceManager.GetString("EnumCustomerType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Cả hai&gt;&gt;.
        /// </summary>
        internal static string EnumCustomerType_All1 {
            get {
                return ResourceManager.GetString("EnumCustomerType_All1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string EnumCustomerType_Customer {
            get {
                return ResourceManager.GetString("EnumCustomerType_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string EnumCustomerType_Supplier {
            get {
                return ResourceManager.GetString("EnumCustomerType_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi.
        /// </summary>
        internal static string EnumRefType_ExpenseVoucher {
            get {
                return ResourceManager.GetString("EnumRefType_ExpenseVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhập kho.
        /// </summary>
        internal static string EnumRefType_InwardVourcher {
            get {
                return ResourceManager.GetString("EnumRefType_InwardVourcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn bán hàng.
        /// </summary>
        internal static string EnumRefType_OutwardVoucher {
            get {
                return ResourceManager.GetString("EnumRefType_OutwardVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu thu.
        /// </summary>
        internal static string EnumRefType_ReceiptVoucher {
            get {
                return ResourceManager.GetString("EnumRefType_ReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cả năm.
        /// </summary>
        internal static string EnumReportPeriod_AllYear {
            get {
                return ResourceManager.GetString("EnumReportPeriod_AllYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 4.
        /// </summary>
        internal static string EnumReportPeriod_April {
            get {
                return ResourceManager.GetString("EnumReportPeriod_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 8.
        /// </summary>
        internal static string EnumReportPeriod_August {
            get {
                return ResourceManager.GetString("EnumReportPeriod_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 12.
        /// </summary>
        internal static string EnumReportPeriod_December {
            get {
                return ResourceManager.GetString("EnumReportPeriod_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 2.
        /// </summary>
        internal static string EnumReportPeriod_February {
            get {
                return ResourceManager.GetString("EnumReportPeriod_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 1.
        /// </summary>
        internal static string EnumReportPeriod_January {
            get {
                return ResourceManager.GetString("EnumReportPeriod_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 7.
        /// </summary>
        internal static string EnumReportPeriod_July {
            get {
                return ResourceManager.GetString("EnumReportPeriod_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 6.
        /// </summary>
        internal static string EnumReportPeriod_June {
            get {
                return ResourceManager.GetString("EnumReportPeriod_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng trước.
        /// </summary>
        internal static string EnumReportPeriod_LastMonth {
            get {
                return ResourceManager.GetString("EnumReportPeriod_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần trước.
        /// </summary>
        internal static string EnumReportPeriod_LastWeek {
            get {
                return ResourceManager.GetString("EnumReportPeriod_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 3.
        /// </summary>
        internal static string EnumReportPeriod_March {
            get {
                return ResourceManager.GetString("EnumReportPeriod_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 5.
        /// </summary>
        internal static string EnumReportPeriod_May {
            get {
                return ResourceManager.GetString("EnumReportPeriod_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 11.
        /// </summary>
        internal static string EnumReportPeriod_November {
            get {
                return ResourceManager.GetString("EnumReportPeriod_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 10.
        /// </summary>
        internal static string EnumReportPeriod_October {
            get {
                return ResourceManager.GetString("EnumReportPeriod_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn.
        /// </summary>
        internal static string EnumReportPeriod_Option {
            get {
                return ResourceManager.GetString("EnumReportPeriod_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý IV.
        /// </summary>
        internal static string EnumReportPeriod_QuarterFour {
            get {
                return ResourceManager.GetString("EnumReportPeriod_QuarterFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý I.
        /// </summary>
        internal static string EnumReportPeriod_QuarterOne {
            get {
                return ResourceManager.GetString("EnumReportPeriod_QuarterOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý III.
        /// </summary>
        internal static string EnumReportPeriod_QuarterThree {
            get {
                return ResourceManager.GetString("EnumReportPeriod_QuarterThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý II.
        /// </summary>
        internal static string EnumReportPeriod_QuarterTwo {
            get {
                return ResourceManager.GetString("EnumReportPeriod_QuarterTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 9.
        /// </summary>
        internal static string EnumReportPeriod_September {
            get {
                return ResourceManager.GetString("EnumReportPeriod_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng này.
        /// </summary>
        internal static string EnumReportPeriod_ThisMonth {
            get {
                return ResourceManager.GetString("EnumReportPeriod_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần này.
        /// </summary>
        internal static string EnumReportPeriod_ThisWeek {
            get {
                return ResourceManager.GetString("EnumReportPeriod_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        internal static string EnumReportPeriod_Today {
            get {
                return ResourceManager.GetString("EnumReportPeriod_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm qua.
        /// </summary>
        internal static string EnumReportPeriod_Yesterday {
            get {
                return ResourceManager.GetString("EnumReportPeriod_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error1 {
            get {
                object obj = ResourceManager.GetObject("error1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công, dữ liệu không hợp lệ..
        /// </summary>
        internal static string Exception_SaveFail {
            get {
                return ResourceManager.GetString("Exception_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file thành công, bạn có muốn mở file vừa xuất không?..
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm viên: {0}.
        /// </summary>
        internal static string FormStatus_User {
            get {
                return ResourceManager.GetString("FormStatus_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày phải nhỏ hơn đến ngày..
        /// </summary>
        internal static string FromDateMustLessThanToDate {
            get {
                return ResourceManager.GetString("FromDateMustLessThanToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập sai thông tin, mời nhập lại!.
        /// </summary>
        internal static string IncorrectInfoReEnter {
            get {
                return ResourceManager.GetString("IncorrectInfoReEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventory32 {
            get {
                object obj = ResourceManager.GetObject("inventory32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice {
            get {
                object obj = ResourceManager.GetObject("invoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap khunghinh {
            get {
                object obj = ResourceManager.GetObject("khunghinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên đăng nhập hoặc mật khẩu..
        /// </summary>
        internal static string lblErrorText_InvalidLogin {
            get {
                return ResourceManager.GetString("lblErrorText_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được bỏ trống..
        /// </summary>
        internal static string lblErrorText_PasswordEmpty {
            get {
                return ResourceManager.GetString("lblErrorText_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được bỏ trống..
        /// </summary>
        internal static string lblErrorText_UserNameEmpty {
            get {
                return ResourceManager.GetString("lblErrorText_UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &lt;&lt;{0}&gt;&gt; không có quyền đăng nhập..
        /// </summary>
        internal static string Login_UserNotPermission {
            get {
                return ResourceManager.GetString("Login_UserNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loi {
            get {
                object obj = ResourceManager.GetObject("loi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loi1 {
            get {
                object obj = ResourceManager.GetObject("loi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playback_pause {
            get {
                object obj = ResourceManager.GetObject("media_playback_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playback_start {
            get {
                object obj = ResourceManager.GetObject("media_playback_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_seek_backward {
            get {
                object obj = ResourceManager.GetObject("media_seek_backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_seek_forward {
            get {
                object obj = ResourceManager.GetObject("media_seek_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thoát khỏi phiên làm việc ?.
        /// </summary>
        internal static string Mess_Logout {
            get {
                return ResourceManager.GetString("Mess_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thông tin.
        /// </summary>
        internal static string MNR_NotInfo {
            get {
                return ResourceManager.GetString("MNR_NotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không khớp!.
        /// </summary>
        internal static string NewPasswordNotRight {
            get {
                return ResourceManager.GetString("NewPasswordNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next2 {
            get {
                object obj = ResourceManager.GetObject("Next2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noImage {
            get {
                object obj = ResourceManager.GetObject("noImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK_button_icon {
            get {
                object obj = ResourceManager.GetObject("OK-button-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap old_go_next {
            get {
                object obj = ResourceManager.GetObject("old_go_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap old_go_previous {
            get {
                object obj = ResourceManager.GetObject("old_go_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng!.
        /// </summary>
        internal static string OldPassNotRight {
            get {
                return ResourceManager.GetString("OldPassNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OutwardInvoice {
            get {
                object obj = ResourceManager.GetObject("OutwardInvoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại!.
        /// </summary>
        internal static string PasswordFailer {
            get {
                return ResourceManager.GetString("PasswordFailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 6 ký tự!.
        /// </summary>
        internal static string PasswordRule0 {
            get {
                return ResourceManager.GetString("PasswordRule0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mạnh của mật khẩu: Yếu.
        /// </summary>
        internal static string PasswordStrength1 {
            get {
                return ResourceManager.GetString("PasswordStrength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mạnh của mật khẩu: Trung Bình.
        /// </summary>
        internal static string PasswordStrength2 {
            get {
                return ResourceManager.GetString("PasswordStrength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mạnh của mật khẩu: Mạnh.
        /// </summary>
        internal static string PasswordStrength3 {
            get {
                return ResourceManager.GetString("PasswordStrength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công!.
        /// </summary>
        internal static string PasswordSuccess {
            get {
                return ResourceManager.GetString("PasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pdp_camera {
            get {
                object obj = ResourceManager.GetObject("pdp-camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Previous {
            get {
                object obj = ResourceManager.GetObject("Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous2 {
            get {
                object obj = ResourceManager.GetObject("previous2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshDocViewHS {
            get {
                object obj = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo không có số liệu..
        /// </summary>
        internal static string Report_NotData {
            get {
                return ResourceManager.GetString("Report_NotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm thu phí: {0}.
        /// </summary>
        internal static string ReportStationFormatString {
            get {
                return ResourceManager.GetString("ReportStationFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên bản giao ca của thu phí viên.
        /// </summary>
        internal static string ReportTitle_BC1 {
            get {
                return ResourceManager.GetString("ReportTitle_BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi đếm xe trong ca.
        /// </summary>
        internal static string ReportTitle_BC2 {
            get {
                return ResourceManager.GetString("ReportTitle_BC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên bản giao ca toàn trạm.
        /// </summary>
        internal static string ReportTitle_BC3 {
            get {
                return ResourceManager.GetString("ReportTitle_BC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh chụp các trường hợp thông xe miễn phí và vé toàn quốc.
        /// </summary>
        internal static string ReportTitle_BC4 {
            get {
                return ResourceManager.GetString("ReportTitle_BC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tổng hợp số thu hàng tháng.
        /// </summary>
        internal static string ReportTitle_BC5 {
            get {
                return ResourceManager.GetString("ReportTitle_BC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi bán vé tháng/quý/kỳ hàng tháng.
        /// </summary>
        internal static string ReportTitle_BC6 {
            get {
                return ResourceManager.GetString("ReportTitle_BC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đếm xe hàng tháng.
        /// </summary>
        internal static string ReportTitle_BC7 {
            get {
                return ResourceManager.GetString("ReportTitle_BC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tổng hợp số thu hàng năm.
        /// </summary>
        internal static string ReportTitle_BC8 {
            get {
                return ResourceManager.GetString("ReportTitle_BC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đếm xe hàng năm.
        /// </summary>
        internal static string ReportTitle_BC9 {
            get {
                return ResourceManager.GetString("ReportTitle_BC9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo theo dõi lưu lượng xe.
        /// </summary>
        internal static string ReportTitle_VehicleCount {
            get {
                return ResourceManager.GetString("ReportTitle_VehicleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị: {0}.
        /// </summary>
        internal static string ReportUnitFormatString {
            get {
                return ResourceManager.GetString("ReportUnitFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save16 {
            get {
                object obj = ResourceManager.GetObject("Save16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Tất cả&gt;&gt;.
        /// </summary>
        internal static string SelectedAllText {
            get {
                return ResourceManager.GetString("SelectedAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stopedit {
            get {
                object obj = ResourceManager.GetObject("stopedit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stopedit1 {
            get {
                object obj = ResourceManager.GetObject("stopedit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Supplier {
            get {
                object obj = ResourceManager.GetObject("Supplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemMonitor16 {
            get {
                object obj = ResourceManager.GetObject("SystemMonitor16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé toàn quốc.
        /// </summary>
        internal static string TcType_AllCountry {
            get {
                return ResourceManager.GetString("TcType_AllCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETC.
        /// </summary>
        internal static string TcType_ETC {
            get {
                return ResourceManager.GetString("TcType_ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé miễn phí theo đoàn.
        /// </summary>
        internal static string TcType_FreeMany {
            get {
                return ResourceManager.GetString("TcType_FreeMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé miễn phí đơn chiếc.
        /// </summary>
        internal static string TcType_FreeOne {
            get {
                return ResourceManager.GetString("TcType_FreeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe vượt trạm.
        /// </summary>
        internal static string TcType_InvalidPass {
            get {
                return ResourceManager.GetString("TcType_InvalidPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé tháng/quý.
        /// </summary>
        internal static string TcType_Month {
            get {
                return ResourceManager.GetString("TcType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé lượt.
        /// </summary>
        internal static string TcType_Turn {
            get {
                return ResourceManager.GetString("TcType_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cả hai.
        /// </summary>
        internal static string Title_AllCustomer {
            get {
                return ResourceManager.GetString("Title_AllCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string Title_Customer {
            get {
                return ResourceManager.GetString("Title_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string Title_Supplier {
            get {
                return ResourceManager.GetString("Title_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toancanh {
            get {
                object obj = ResourceManager.GetObject("toancanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chưa được nhập.
        /// </summary>
        internal static string txtEnter {
            get {
                return ResourceManager.GetString("txtEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up4 {
            get {
                object obj = ResourceManager.GetObject("up4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại..
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User_Boy {
            get {
                object obj = ResourceManager.GetObject("User_Boy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xe không khớp với lịch sử xe qua trạm..
        /// </summary>
        internal static string VehicleHistoryVerifyInvalid {
            get {
                return ResourceManager.GetString("VehicleHistoryVerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xe khớp với lịch sử xe qua trạm..
        /// </summary>
        internal static string VehicleHistoryVerifyValid {
            get {
                return ResourceManager.GetString("VehicleHistoryVerifyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video1 {
            get {
                object obj = ResourceManager.GetObject("video1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warehousing {
            get {
                object obj = ResourceManager.GetObject("warehousing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được xóa nhóm đã có đối tượng con..
        /// </summary>
        internal static string Warning_AccountingObjectCategory_NotDeleteItemHasChild {
            get {
                return ResourceManager.GetString("Warning_AccountingObjectCategory_NotDeleteItemHasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;{0}&gt;&gt; đã tồn tại trong hệ thống..
        /// </summary>
        internal static string Warning_DupplicateCode {
            get {
                return ResourceManager.GetString("Warning_DupplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập dòng chi tiết..
        /// </summary>
        internal static string Warning_MustEnterDetail {
            get {
                return ResourceManager.GetString("Warning_MustEnterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được chọn danh mục cha..
        /// </summary>
        internal static string Warning_NotSelectParent {
            get {
                return ResourceManager.GetString("Warning_NotSelectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xanh {
            get {
                object obj = ResourceManager.GetObject("Xanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xanh1 {
            get {
                object obj = ResourceManager.GetObject("Xanh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử lại.
        /// </summary>
        internal static string XtraMessage__Retry {
            get {
                return ResourceManager.GetString("XtraMessage__Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng.
        /// </summary>
        internal static string XtraMessage_Abort {
            get {
                return ResourceManager.GetString("XtraMessage_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string XtraMessage_Cancel {
            get {
                return ResourceManager.GetString("XtraMessage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        internal static string XtraMessage_Ignore {
            get {
                return ResourceManager.GetString("XtraMessage_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        internal static string XtraMessage_No {
            get {
                return ResourceManager.GetString("XtraMessage_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string XtraMessage_Ok {
            get {
                return ResourceManager.GetString("XtraMessage_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        internal static string XtraMessage_Yes {
            get {
                return ResourceManager.GetString("XtraMessage_Yes", resourceCulture);
            }
        }
    }
}
